#!/bin/bash

## Copyright (c) 2024 mangalbhaskar. All Rights Reserved.
##__author__ = 'mangalbhaskar'
###----------------------------------------------------------
## color utility functions
###----------------------------------------------------------


function lsd-mod.color.get__vars() {
  lsd-mod.log.echo "nocolor: ${nocolor}             nocolor       "
  lsd-mod.log.echo "bla: ${bla}                 bla           "
  lsd-mod.log.echo "bbla: ${bbla}                bbla          "
  lsd-mod.log.echo "ubla: ${ubla}                ubla          "
  lsd-mod.log.echo "ibla: ${ibla}                ibla          "
  lsd-mod.log.echo "bibla: ${bibla}               bibla         "
  lsd-mod.log.echo "on_bla: ${on_bla}              on_bla        "
  lsd-mod.log.echo "on_ibla: ${on_ibla}             on_ibla       "
  lsd-mod.log.echo "red: ${red}                 red           "
  lsd-mod.log.echo "bred: ${bred}                bred          "
  lsd-mod.log.echo "ured: ${ured}                ured          "
  lsd-mod.log.echo "ired: ${ired}                ired          "
  lsd-mod.log.echo "bired: ${bired}               bired         "
  lsd-mod.log.echo "on_red: ${on_red}              on_red        "
  lsd-mod.log.echo "on_ired: ${on_ired}             on_ired       "
  lsd-mod.log.echo "gre: ${gre}                 gre           "
  lsd-mod.log.echo "bgre: ${bgre}                bgre          "
  lsd-mod.log.echo "ugre: ${ugre}                ugre          "
  lsd-mod.log.echo "igre: ${igre}                igre          "
  lsd-mod.log.echo "bigre: ${bigre}               bigre         "
  lsd-mod.log.echo "on_gre: ${on_gre}              on_gre        "
  lsd-mod.log.echo "on_igre: ${on_igre}             on_igre       "
  lsd-mod.log.echo "yel: ${yel}                 yel           "
  lsd-mod.log.echo "byel: ${byel}                byel          "
  lsd-mod.log.echo "uyel: ${uyel}                uyel          "
  lsd-mod.log.echo "iyel: ${iyel}                iyel          "
  lsd-mod.log.echo "biyel: ${biyel}               biyel         "
  lsd-mod.log.echo "on_yel: ${on_yel}              on_yel        "
  lsd-mod.log.echo "on_iyel: ${on_iyel}             on_iyel       "
  lsd-mod.log.echo "blu: ${blu}                 blu           "
  lsd-mod.log.echo "bblu: ${bblu}                bblu          "
  lsd-mod.log.echo "ublu: ${ublu}                ublu          "
  lsd-mod.log.echo "iblu: ${iblu}                iblu          "
  lsd-mod.log.echo "biblu: ${biblu}               biblu         "
  lsd-mod.log.echo "on_blu: ${on_blu}              on_blu        "
  lsd-mod.log.echo "on_iblu: ${on_iblu}             on_iblu       "
  lsd-mod.log.echo "pur: ${pur}                 pur           "
  lsd-mod.log.echo "bpur: ${bpur}                bpur          "
  lsd-mod.log.echo "upur: ${upur}                upur          "
  lsd-mod.log.echo "ipur: ${ipur}                ipur          "
  lsd-mod.log.echo "bipur: ${bipur}               bipur         "
  lsd-mod.log.echo "on_pur: ${on_pur}              on_pur        "
  lsd-mod.log.echo "on_ipur: ${on_ipur}             on_ipur       "
  lsd-mod.log.echo "cya: ${cya}                 cya           "
  lsd-mod.log.echo "bcya: ${bcya}                bcya          "
  lsd-mod.log.echo "ucya: ${ucya}                ucya          "
  lsd-mod.log.echo "icya: ${icya}                icya          "
  lsd-mod.log.echo "bicya: ${bicya}               bicya         "
  lsd-mod.log.echo "on_cya: ${on_cya}              on_cya        "
  lsd-mod.log.echo "on_icya: ${on_icya}             on_icya       "
  lsd-mod.log.echo "whi: ${whi}                 whi           "
  lsd-mod.log.echo "bwhi: ${bwhi}                bwhi          "
  lsd-mod.log.echo "uwhi: ${uwhi}                uwhi          "
  lsd-mod.log.echo "iwhi: ${iwhi}                iwhi          "
  lsd-mod.log.echo "biwhi: ${biwhi}               biwhi         "
  lsd-mod.log.echo "on_whi: ${on_whi}              on_whi        "
  lsd-mod.log.echo "on_iwhi: ${on_iwhi}             on_iwhi       "
}
