#!/bin/bash

## Copyright (c) 2021 mangalbhaskar. All Rights Reserved.
##__author__ = 'mangalbhaskar'
##----------------------------------------------------------
## formats
##----------------------------------------------------------

local __TIMESTAMP__=$(date -d now +'%d%m%y_%H%M%S')

local _BANNER_="This file is autogenerated and will be overwritten!"
local _SHEBANG_="#!/bin/bash"
local _COPYRIGHT_="Copyright (c) 2021 mangalbhaskar"
